# Generated by Django 5.0.2 on 2024-02-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_user_followed_by_alter_post_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
    ]
