# Generated by Django 5.0.2 on 2024-02-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_remove_post_like_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="followed_by",
            new_name="following",
        ),
    ]
