# Generated by Django 5.0.2 on 2024-02-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_rename_followed_by_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
    ]
